services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=dsc202friends
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=booksdb
    volumes:
      - .:/app
    depends_on:
      - neo4j
      - postgres

  neo4j:
    image: neo4j:5.14.0
    container_name: neo4j-database
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/dsc202friends
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms.memory.heap.initial_size=8G
      - NEO4J_dbms_memory_heap_max__size=16G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

  postgres:
    image: postgres:14
    container_name: postgres-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=booksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
  postgres_data: